#!/usr/bin/env bash
# nstall and configure HAproxy on your lb-01 server.
# Send traffic to web-O1 and web-02 servers using a roundrobin algorithm

sudo apt install -y haproxy
sudo sed -i '35 a frontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n'  /etc/haproxy/haproxy.cfg
sudo sed -i '40 a backend web-backend\n\tbalance roundrobin\n\tmode http\n\tserver node1 34.138.32.10:80 check\n\tserver node2 34.237.53.89:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
