#!/usr/bin/env bash
# This script is displaying "Best  School" 9 times and hi at the teenth stage
count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
