#!/usr/bin/env bash
# runs nginx as 'nginx' user (7 or less lines script)
chmod 755 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
pkill -f "apache2"
sudo -u nginx service nginx restart
